name: Hello

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files
        run: | 
         pwd
         ls
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Simple JS actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Ranjan
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time}}"
    